---
require:
 - rubocop-rspec
AllCops:
  Include:
  - "lib/**/*.rb"
  Exclude:
  - bin/*
  - ".vendor/**/*"
  - Gemfile
  - Rakefile
  - pkg/**/*
  - spec/fixtures/**/*
  - vendor/**/*
Metrics/LineLength:
  Description: People have wide screens, use them.
  Max: 200
  Enabled: false
RSpec/BeforeAfterAll:
  Description: Beware of using after(:all) as it may cause state to leak between tests.
    A necessary evil in acceptance testing.
  Exclude:
  - spec/acceptance/**/*.rb
RSpec/HookArgument:
  Description: Prefer explicit :each argument, matching existing module's style
  EnforcedStyle: each
Style/BlockDelimiters:
  Description: Prefer braces for chaining. Mostly an aesthetical choice. Better to
    be consistent then.
  EnforcedStyle: semantic
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/*
  - lib/puppet/type/*
Style/ClassAndModuleChildren:
  Description: Compact style reduces the required amount of indentation.
  EnforcedStyle: compact
Style/EmptyElse:
  Description: Enforce against empty else clauses, but allow `nil` for clarity.
  EnforcedStyle: empty
Style/FormatString:
  Description: Following the main puppet project's style, prefer the % format format.
  EnforcedStyle: percent
  Exclude:
Style/FormatStringToken:
  Description: Following the main puppet project's style, prefer the simpler template
    tokens over annotated ones.
  EnforcedStyle: template
Style/Lambda:
  Description: Prefer the keyword for easier discoverability.
  EnforcedStyle: literal
  Enabled: true
  Exclude:
Style/RegexpLiteral:
  Description: Community preference. See https://github.com/voxpupuli/modulesync_config/issues/168
  EnforcedStyle: percent_r
Style/StringLiterals:
  Enabled: true
  Exclude:
  - autogen_type.rb
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
  - lib/puppet/type/azure* 
Style/TernaryParentheses:
  Description: Checks for use of parentheses around ternary conditions. Enforce parentheses
    on complex expressions for better readability, but seriously consider breaking
    it up.
  EnforcedStyle: require_parentheses_when_complex
Style/SymbolArray:
  Description: Using percent style obscures symbolic intent of array's contents.
  EnforcedStyle: brackets
Style/CollectionMethods:
  Enabled: true
Style/MethodCalledOnDoEndBlock:
  Enabled: true
Style/StringMethods:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/MessageExpectation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines
Style/HashSyntax:
  UseHashRocketsWithSymbolValues: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
  - lib/puppet/type/azure*
Style/RedundantReturn:
  Enabled: true
  Exclude:
  - autogen_type.rb
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
  - lib/puppet/type/azure*
Style/RedundantSelf:
  Enabled: true
  Exclude: 
  - autogen_type.rb
  - autogen_provider.rb 
  - lib/puppet/provider/**/azure*
  - lib/puppet/type/azure* 
Style/NegatedIf:
  Enabled: true
  Exclude:
  - autogen_type.rb
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
  - lib/puppet/type/azure*
Style/GuardClause:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
  - lib/puppet/type/azure*
Style/CollectionMethods:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
  - lib/puppet/type/azure*
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
  - lib/puppet/type/azure*
Style/TrailingCommaInHashLiteral:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
  - lib/puppet/type/azure*
Style/ClassCheck:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
Style/AndOr:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
Style/MethodCalledOnDoEndBlock:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
Style/IfInsideElse:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
Layout/EmptyLines:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
Layout/EmptyLineBetweenDefs:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
Lint/UnusedMethodArgument:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
  - lib/puppet/type/azure*
Lint/RescueException:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*
  - lib/puppet/type/azure*
Lint/UnusedBlockArgument:
  Enabled: true
  Exclude:
   - autogen_type.rb
   - autogen_provider.rb 
   - lib/puppet/provider/**/azure*
   - lib/puppet/type/azure*
Naming/PredicateName:
  Enabled: true
  Exclude:
  - autogen_provider.rb
  - lib/puppet/provider/**/azure*